image_text_extraction_task:
  description: >
    Make sure you extract the data from the provoded {image_url}.
  expected_output: >
    All teh text exists in the data
  agent: image_text_extraction_agent